package at.fhv.xmltool.carrental.jpa;
// Generated 17.01.2018 18:27:00 by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JPAAutotyp generated by hbm2java
 */
@Entity
@Table(name="autotyp"
    ,schema="public"
)
public class JPAAutotyp  implements java.io.Serializable {


     private String typBezeichnung;
     private JPAAutokategorie JPAAutokategorie;
     private BigDecimal benzinverbrauch;
     private Set<JPAExtraausstattung> JPAExtraausstattungs = new HashSet<JPAExtraausstattung>(0);
     private Set<JPAAuto> JPAAutos = new HashSet<JPAAuto>(0);

    public JPAAutotyp() {
    }

	
    public JPAAutotyp(String typBezeichnung) {
        this.typBezeichnung = typBezeichnung;
    }
    public JPAAutotyp(String typBezeichnung, JPAAutokategorie JPAAutokategorie, BigDecimal benzinverbrauch, Set<JPAExtraausstattung> JPAExtraausstattungs, Set<JPAAuto> JPAAutos) {
       this.typBezeichnung = typBezeichnung;
       this.JPAAutokategorie = JPAAutokategorie;
       this.benzinverbrauch = benzinverbrauch;
       this.JPAExtraausstattungs = JPAExtraausstattungs;
       this.JPAAutos = JPAAutos;
    }
   
     @Id 

    
    @Column(name="typ_bezeichnung", unique=true, nullable=false, length=8)
    public String getTypBezeichnung() {
        return this.typBezeichnung;
    }
    
    public void setTypBezeichnung(String typBezeichnung) {
        this.typBezeichnung = typBezeichnung;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="kategorie_bezeichnung")
    public JPAAutokategorie getJPAAutokategorie() {
        return this.JPAAutokategorie;
    }
    
    public void setJPAAutokategorie(JPAAutokategorie JPAAutokategorie) {
        this.JPAAutokategorie = JPAAutokategorie;
    }

    
    @Column(name="benzinverbrauch", precision=4)
    public BigDecimal getBenzinverbrauch() {
        return this.benzinverbrauch;
    }
    
    public void setBenzinverbrauch(BigDecimal benzinverbrauch) {
        this.benzinverbrauch = benzinverbrauch;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="JPAAutotyp")
    public Set<JPAExtraausstattung> getJPAExtraausstattungs() {
        return this.JPAExtraausstattungs;
    }
    
    public void setJPAExtraausstattungs(Set<JPAExtraausstattung> JPAExtraausstattungs) {
        this.JPAExtraausstattungs = JPAExtraausstattungs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="JPAAutotyp")
    public Set<JPAAuto> getJPAAutos() {
        return this.JPAAutos;
    }
    
    public void setJPAAutos(Set<JPAAuto> JPAAutos) {
        this.JPAAutos = JPAAutos;
    }




}


