package at.fhv.xmltool.carrental.jpa;
// Generated 17.01.2018 18:27:00 by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JPAAutokategorie generated by hbm2java
 */
@Entity
@Table(name="autokategorie"
    ,schema="public"
)
public class JPAAutokategorie  implements java.io.Serializable {


     private String kategorieBezeichnung;
     private BigDecimal grundtarif;
     private BigDecimal kmPreis;
     private Set<JPAReservierung> JPAReservierungs = new HashSet<JPAReservierung>(0);
     private Set<JPAAutotyp> JPAAutotyps = new HashSet<JPAAutotyp>(0);

    public JPAAutokategorie() {
    }

	
    public JPAAutokategorie(String kategorieBezeichnung) {
        this.kategorieBezeichnung = kategorieBezeichnung;
    }
    public JPAAutokategorie(String kategorieBezeichnung, BigDecimal grundtarif, BigDecimal kmPreis, Set<JPAReservierung> JPAReservierungs, Set<JPAAutotyp> JPAAutotyps) {
       this.kategorieBezeichnung = kategorieBezeichnung;
       this.grundtarif = grundtarif;
       this.kmPreis = kmPreis;
       this.JPAReservierungs = JPAReservierungs;
       this.JPAAutotyps = JPAAutotyps;
    }
   
     @Id 

    
    @Column(name="kategorie_bezeichnung", unique=true, nullable=false, length=3)
    public String getKategorieBezeichnung() {
        return this.kategorieBezeichnung;
    }
    
    public void setKategorieBezeichnung(String kategorieBezeichnung) {
        this.kategorieBezeichnung = kategorieBezeichnung;
    }

    
    @Column(name="grundtarif", scale=4)
    public BigDecimal getGrundtarif() {
        return this.grundtarif;
    }
    
    public void setGrundtarif(BigDecimal grundtarif) {
        this.grundtarif = grundtarif;
    }

    
    @Column(name="km_preis", scale=4)
    public BigDecimal getKmPreis() {
        return this.kmPreis;
    }
    
    public void setKmPreis(BigDecimal kmPreis) {
        this.kmPreis = kmPreis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="JPAAutokategorie")
    public Set<JPAReservierung> getJPAReservierungs() {
        return this.JPAReservierungs;
    }
    
    public void setJPAReservierungs(Set<JPAReservierung> JPAReservierungs) {
        this.JPAReservierungs = JPAReservierungs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="JPAAutokategorie")
    public Set<JPAAutotyp> getJPAAutotyps() {
        return this.JPAAutotyps;
    }
    
    public void setJPAAutotyps(Set<JPAAutotyp> JPAAutotyps) {
        this.JPAAutotyps = JPAAutotyps;
    }




}


