package at.fhv.xmltool.carrental.jpa;
// Generated 17.01.2018 18:27:00 by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JPAExtraausstattung generated by hbm2java
 */
@Entity
@Table(name="extraausstattung"
    ,schema="public"
)
public class JPAExtraausstattung  implements java.io.Serializable {


     private JPAExtraausstattungId id;
     private JPAAutotyp JPAAutotyp;
     private BigDecimal aufpreis;
     private Set<JPAAuto> JPAAutos = new HashSet<JPAAuto>(0);

    public JPAExtraausstattung() {
    }

	
    public JPAExtraausstattung(JPAExtraausstattungId id, JPAAutotyp JPAAutotyp) {
        this.id = id;
        this.JPAAutotyp = JPAAutotyp;
    }
    public JPAExtraausstattung(JPAExtraausstattungId id, JPAAutotyp JPAAutotyp, BigDecimal aufpreis, Set<JPAAuto> JPAAutos) {
       this.id = id;
       this.JPAAutotyp = JPAAutotyp;
       this.aufpreis = aufpreis;
       this.JPAAutos = JPAAutos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="typBezeichnung", column=@Column(name="typ_bezeichnung", nullable=false, length=8) ), 
        @AttributeOverride(name="extrasBezeichnung", column=@Column(name="extras_bezeichnung", nullable=false, length=8) ) } )
    public JPAExtraausstattungId getId() {
        return this.id;
    }
    
    public void setId(JPAExtraausstattungId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="typ_bezeichnung", nullable=false, insertable=false, updatable=false)
    public JPAAutotyp getJPAAutotyp() {
        return this.JPAAutotyp;
    }
    
    public void setJPAAutotyp(JPAAutotyp JPAAutotyp) {
        this.JPAAutotyp = JPAAutotyp;
    }

    
    @Column(name="aufpreis", scale=4)
    public BigDecimal getAufpreis() {
        return this.aufpreis;
    }
    
    public void setAufpreis(BigDecimal aufpreis) {
        this.aufpreis = aufpreis;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="verfuegt_ueber", schema="public", joinColumns = { 
        @JoinColumn(name="typ_bezeichnung", nullable=false, updatable=false), 
        @JoinColumn(name="extras_bezeichnung", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="kennzeichen", nullable=false, updatable=false) })
    public Set<JPAAuto> getJPAAutos() {
        return this.JPAAutos;
    }
    
    public void setJPAAutos(Set<JPAAuto> JPAAutos) {
        this.JPAAutos = JPAAutos;
    }




}


