package at.fhv.xmltool.carrental.jpa;
// Generated 17.01.2018 18:27:00 by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JPAExtraausstattungId generated by hbm2java
 */
@Embeddable
public class JPAExtraausstattungId  implements java.io.Serializable {


     private String typBezeichnung;
     private String extrasBezeichnung;

    public JPAExtraausstattungId() {
    }

    public JPAExtraausstattungId(String typBezeichnung, String extrasBezeichnung) {
       this.typBezeichnung = typBezeichnung;
       this.extrasBezeichnung = extrasBezeichnung;
    }
   


    @Column(name="typ_bezeichnung", nullable=false, length=8)
    public String getTypBezeichnung() {
        return this.typBezeichnung;
    }
    
    public void setTypBezeichnung(String typBezeichnung) {
        this.typBezeichnung = typBezeichnung;
    }


    @Column(name="extras_bezeichnung", nullable=false, length=8)
    public String getExtrasBezeichnung() {
        return this.extrasBezeichnung;
    }
    
    public void setExtrasBezeichnung(String extrasBezeichnung) {
        this.extrasBezeichnung = extrasBezeichnung;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JPAExtraausstattungId) ) return false;
		 JPAExtraausstattungId castOther = ( JPAExtraausstattungId ) other; 
         
		 return ( (this.getTypBezeichnung()==castOther.getTypBezeichnung()) || ( this.getTypBezeichnung()!=null && castOther.getTypBezeichnung()!=null && this.getTypBezeichnung().equals(castOther.getTypBezeichnung()) ) )
 && ( (this.getExtrasBezeichnung()==castOther.getExtrasBezeichnung()) || ( this.getExtrasBezeichnung()!=null && castOther.getExtrasBezeichnung()!=null && this.getExtrasBezeichnung().equals(castOther.getExtrasBezeichnung()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTypBezeichnung() == null ? 0 : this.getTypBezeichnung().hashCode() );
         result = 37 * result + ( getExtrasBezeichnung() == null ? 0 : this.getExtrasBezeichnung().hashCode() );
         return result;
   }   


}


