package at.fhv.xmltool.carrental.jpa;
// Generated 17.01.2018 18:27:00 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JPAKunde generated by hbm2java
 */
@Entity
@Table(name="kunde"
    ,schema="public"
)
public class JPAKunde  implements java.io.Serializable {


     private String fuehrerscheinNummer;
     private String kundeName;
     private String anschrift;
     private Set<JPAReservierung> JPAReservierungs = new HashSet<JPAReservierung>(0);

    public JPAKunde() {
    }

	
    public JPAKunde(String fuehrerscheinNummer) {
        this.fuehrerscheinNummer = fuehrerscheinNummer;
    }
    public JPAKunde(String fuehrerscheinNummer, String kundeName, String anschrift, Set<JPAReservierung> JPAReservierungs) {
       this.fuehrerscheinNummer = fuehrerscheinNummer;
       this.kundeName = kundeName;
       this.anschrift = anschrift;
       this.JPAReservierungs = JPAReservierungs;
    }
   
     @Id 

    
    @Column(name="fuehrerschein_nummer", unique=true, nullable=false, length=8)
    public String getFuehrerscheinNummer() {
        return this.fuehrerscheinNummer;
    }
    
    public void setFuehrerscheinNummer(String fuehrerscheinNummer) {
        this.fuehrerscheinNummer = fuehrerscheinNummer;
    }

    
    @Column(name="kunde_name")
    public String getKundeName() {
        return this.kundeName;
    }
    
    public void setKundeName(String kundeName) {
        this.kundeName = kundeName;
    }

    
    @Column(name="anschrift")
    public String getAnschrift() {
        return this.anschrift;
    }
    
    public void setAnschrift(String anschrift) {
        this.anschrift = anschrift;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="JPAKunde")
    public Set<JPAReservierung> getJPAReservierungs() {
        return this.JPAReservierungs;
    }
    
    public void setJPAReservierungs(Set<JPAReservierung> JPAReservierungs) {
        this.JPAReservierungs = JPAReservierungs;
    }




}


