package at.fhv.xmltool.carrental.jpa;
// Generated 17.01.2018 18:27:00 by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * JPAMietvertrag generated by hbm2java
 */
@Entity
@Table(name="mietvertrag"
    ,schema="public"
)
public class JPAMietvertrag  implements java.io.Serializable {


     private JPAMietvertragId id;
     private JPAReservierung JPAReservierung;
     private Integer kmStandUebergabe;
     private Integer kmStandRueckgabe;

    public JPAMietvertrag() {
    }

	
    public JPAMietvertrag(JPAReservierung JPAReservierung) {
        this.JPAReservierung = JPAReservierung;
    }
    public JPAMietvertrag(JPAReservierung JPAReservierung, Integer kmStandUebergabe, Integer kmStandRueckgabe) {
       this.JPAReservierung = JPAReservierung;
       this.kmStandUebergabe = kmStandUebergabe;
       this.kmStandRueckgabe = kmStandRueckgabe;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="stadtcode", column=@Column(name="stadtcode", nullable=false, length=3) ), 
        @AttributeOverride(name="stationsName", column=@Column(name="stations_name", nullable=false, length=20) ), 
        @AttributeOverride(name="reservierungsNr", column=@Column(name="reservierungs_nr", nullable=false, length=8) ) } )
    public JPAMietvertragId getId() {
        return this.id;
    }
    
    public void setId(JPAMietvertragId id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public JPAReservierung getJPAReservierung() {
        return this.JPAReservierung;
    }
    
    public void setJPAReservierung(JPAReservierung JPAReservierung) {
        this.JPAReservierung = JPAReservierung;
    }

    
    @Column(name="km_stand_uebergabe", precision=6, scale=0)
    public Integer getKmStandUebergabe() {
        return this.kmStandUebergabe;
    }
    
    public void setKmStandUebergabe(Integer kmStandUebergabe) {
        this.kmStandUebergabe = kmStandUebergabe;
    }

    
    @Column(name="km_stand_rueckgabe", precision=6, scale=0)
    public Integer getKmStandRueckgabe() {
        return this.kmStandRueckgabe;
    }
    
    public void setKmStandRueckgabe(Integer kmStandRueckgabe) {
        this.kmStandRueckgabe = kmStandRueckgabe;
    }




}


