package at.fhv.xmltool.carrental.jpa;
// Generated 17.01.2018 18:27:00 by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JPAMietvertragId generated by hbm2java
 */
@Embeddable
public class JPAMietvertragId  implements java.io.Serializable {


     private String stadtcode;
     private String stationsName;
     private String reservierungsNr;

    public JPAMietvertragId() {
    }

    public JPAMietvertragId(String stadtcode, String stationsName, String reservierungsNr) {
       this.stadtcode = stadtcode;
       this.stationsName = stationsName;
       this.reservierungsNr = reservierungsNr;
    }
   


    @Column(name="stadtcode", nullable=false, length=3)
    public String getStadtcode() {
        return this.stadtcode;
    }
    
    public void setStadtcode(String stadtcode) {
        this.stadtcode = stadtcode;
    }


    @Column(name="stations_name", nullable=false, length=20)
    public String getStationsName() {
        return this.stationsName;
    }
    
    public void setStationsName(String stationsName) {
        this.stationsName = stationsName;
    }


    @Column(name="reservierungs_nr", nullable=false, length=8)
    public String getReservierungsNr() {
        return this.reservierungsNr;
    }
    
    public void setReservierungsNr(String reservierungsNr) {
        this.reservierungsNr = reservierungsNr;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JPAMietvertragId) ) return false;
		 JPAMietvertragId castOther = ( JPAMietvertragId ) other; 
         
		 return ( (this.getStadtcode()==castOther.getStadtcode()) || ( this.getStadtcode()!=null && castOther.getStadtcode()!=null && this.getStadtcode().equals(castOther.getStadtcode()) ) )
 && ( (this.getStationsName()==castOther.getStationsName()) || ( this.getStationsName()!=null && castOther.getStationsName()!=null && this.getStationsName().equals(castOther.getStationsName()) ) )
 && ( (this.getReservierungsNr()==castOther.getReservierungsNr()) || ( this.getReservierungsNr()!=null && castOther.getReservierungsNr()!=null && this.getReservierungsNr().equals(castOther.getReservierungsNr()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStadtcode() == null ? 0 : this.getStadtcode().hashCode() );
         result = 37 * result + ( getStationsName() == null ? 0 : this.getStationsName().hashCode() );
         result = 37 * result + ( getReservierungsNr() == null ? 0 : this.getReservierungsNr().hashCode() );
         return result;
   }   


}


