package at.fhv.xmltool.carrental.jpa;
// Generated 17.01.2018 18:27:00 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JPAReservierung generated by hbm2java
 */
@Entity
@Table(name="reservierung"
    ,schema="public"
)
public class JPAReservierung  implements java.io.Serializable {


     private JPAReservierungId id;
     private JPAAutokategorie JPAAutokategorie;
     private JPAKunde JPAKunde;
     private JPAVermietstation JPAVermietstation;
     private Date anfangsdatum;
     private Date enddatum;
     private JPAMietvertrag JPAMietvertrag;

    public JPAReservierung() {
    }

	
    public JPAReservierung(JPAReservierungId id, JPAVermietstation JPAVermietstation) {
        this.id = id;
        this.JPAVermietstation = JPAVermietstation;
    }
    public JPAReservierung(JPAReservierungId id, JPAAutokategorie JPAAutokategorie, JPAKunde JPAKunde, JPAVermietstation JPAVermietstation, Date anfangsdatum, Date enddatum, JPAMietvertrag JPAMietvertrag) {
       this.id = id;
       this.JPAAutokategorie = JPAAutokategorie;
       this.JPAKunde = JPAKunde;
       this.JPAVermietstation = JPAVermietstation;
       this.anfangsdatum = anfangsdatum;
       this.enddatum = enddatum;
       this.JPAMietvertrag = JPAMietvertrag;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="stadtcode", column=@Column(name="stadtcode", nullable=false, length=3) ), 
        @AttributeOverride(name="stationsName", column=@Column(name="stations_name", nullable=false, length=20) ), 
        @AttributeOverride(name="reservierungsNr", column=@Column(name="reservierungs_nr", nullable=false, length=8) ) } )
    public JPAReservierungId getId() {
        return this.id;
    }
    
    public void setId(JPAReservierungId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="kategorie_bezeichnung")
    public JPAAutokategorie getJPAAutokategorie() {
        return this.JPAAutokategorie;
    }
    
    public void setJPAAutokategorie(JPAAutokategorie JPAAutokategorie) {
        this.JPAAutokategorie = JPAAutokategorie;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fuehrerschein_nummer")
    public JPAKunde getJPAKunde() {
        return this.JPAKunde;
    }
    
    public void setJPAKunde(JPAKunde JPAKunde) {
        this.JPAKunde = JPAKunde;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="stadtcode", referencedColumnName="stadtcode", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="stations_name", referencedColumnName="stations_name", nullable=false, insertable=false, updatable=false) } )
    public JPAVermietstation getJPAVermietstation() {
        return this.JPAVermietstation;
    }
    
    public void setJPAVermietstation(JPAVermietstation JPAVermietstation) {
        this.JPAVermietstation = JPAVermietstation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="anfangsdatum", length=13)
    public Date getAnfangsdatum() {
        return this.anfangsdatum;
    }
    
    public void setAnfangsdatum(Date anfangsdatum) {
        this.anfangsdatum = anfangsdatum;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="enddatum", length=13)
    public Date getEnddatum() {
        return this.enddatum;
    }
    
    public void setEnddatum(Date enddatum) {
        this.enddatum = enddatum;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="JPAReservierung")
    public JPAMietvertrag getJPAMietvertrag() {
        return this.JPAMietvertrag;
    }
    
    public void setJPAMietvertrag(JPAMietvertrag JPAMietvertrag) {
        this.JPAMietvertrag = JPAMietvertrag;
    }




}


