package at.fhv.xmltool.carrental.jpa;
// Generated 17.01.2018 18:27:00 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JPAVermietstation generated by hbm2java
 */
@Entity
@Table(name="vermietstation"
    ,schema="public"
)
public class JPAVermietstation  implements java.io.Serializable {


     private JPAVermietstationId id;
     private JPAStadt JPAStadt;
     private String adresse;
     private Integer mitarbeiterAnzahl;
     private Set<JPAAuto> JPAAutos = new HashSet<JPAAuto>(0);
     private Set<JPAReservierung> JPAReservierungs = new HashSet<JPAReservierung>(0);

    public JPAVermietstation() {
    }

	
    public JPAVermietstation(JPAVermietstationId id, JPAStadt JPAStadt) {
        this.id = id;
        this.JPAStadt = JPAStadt;
    }
    public JPAVermietstation(JPAVermietstationId id, JPAStadt JPAStadt, String adresse, Integer mitarbeiterAnzahl, Set<JPAAuto> JPAAutos, Set<JPAReservierung> JPAReservierungs) {
       this.id = id;
       this.JPAStadt = JPAStadt;
       this.adresse = adresse;
       this.mitarbeiterAnzahl = mitarbeiterAnzahl;
       this.JPAAutos = JPAAutos;
       this.JPAReservierungs = JPAReservierungs;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="stadtcode", column=@Column(name="stadtcode", nullable=false, length=3) ), 
        @AttributeOverride(name="stationsName", column=@Column(name="stations_name", nullable=false, length=20) ) } )
    public JPAVermietstationId getId() {
        return this.id;
    }
    
    public void setId(JPAVermietstationId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stadtcode", nullable=false, insertable=false, updatable=false)
    public JPAStadt getJPAStadt() {
        return this.JPAStadt;
    }
    
    public void setJPAStadt(JPAStadt JPAStadt) {
        this.JPAStadt = JPAStadt;
    }

    
    @Column(name="adresse")
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="mitarbeiter_anzahl")
    public Integer getMitarbeiterAnzahl() {
        return this.mitarbeiterAnzahl;
    }
    
    public void setMitarbeiterAnzahl(Integer mitarbeiterAnzahl) {
        this.mitarbeiterAnzahl = mitarbeiterAnzahl;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="JPAVermietstation")
    public Set<JPAAuto> getJPAAutos() {
        return this.JPAAutos;
    }
    
    public void setJPAAutos(Set<JPAAuto> JPAAutos) {
        this.JPAAutos = JPAAutos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="JPAVermietstation")
    public Set<JPAReservierung> getJPAReservierungs() {
        return this.JPAReservierungs;
    }
    
    public void setJPAReservierungs(Set<JPAReservierung> JPAReservierungs) {
        this.JPAReservierungs = JPAReservierungs;
    }




}


