package at.fhv.xmltool.messages2.jpa;
// Generated 14.01.2018 20:01:08 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * JPAMessage generated by hbm2java
 */
@Entity
@Table(name="MESSAGES"
    ,schema="APP"
)
public class JPAMessage  implements java.io.Serializable {


     private Integer id;
     private String fromAdr;
     private String toAdr;
     private String subject;
     private String body;
     private Set<JPARepliedMessage> JPARepliedMessages = new HashSet<JPARepliedMessage>(0);

    public JPAMessage() {
    }

	
    public JPAMessage(String fromAdr, String toAdr, String subject) {
        this.fromAdr = fromAdr;
        this.toAdr = toAdr;
        this.subject = subject;
    }
    public JPAMessage(String fromAdr, String toAdr, String subject, String body, Set<JPARepliedMessage> JPARepliedMessages) {
       this.fromAdr = fromAdr;
       this.toAdr = toAdr;
       this.subject = subject;
       this.body = body;
       this.JPARepliedMessages = JPARepliedMessages;
    }
   
     @GenericGenerator(name="generator", strategy="increment")@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="FROM_ADR", nullable=false)
    public String getFromAdr() {
        return this.fromAdr;
    }
    
    public void setFromAdr(String fromAdr) {
        this.fromAdr = fromAdr;
    }

    
    @Column(name="TO_ADR", nullable=false)
    public String getToAdr() {
        return this.toAdr;
    }
    
    public void setToAdr(String toAdr) {
        this.toAdr = toAdr;
    }

    
    @Column(name="SUBJECT", nullable=false)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="BODY", length=30000)
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="JPAMessage")
    public Set<JPARepliedMessage> getJPARepliedMessages() {
        return this.JPARepliedMessages;
    }
    
    public void setJPARepliedMessages(Set<JPARepliedMessage> JPARepliedMessages) {
        this.JPARepliedMessages = JPARepliedMessages;
    }




}


