package at.fhv.xmltool.messages2.jpa;
// Generated 14.01.2018 20:01:08 by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * JPARepliedMessage generated by hbm2java
 */
@Entity
@Table(name="REPLIED_MESSAGES"
    ,schema="APP"
)
public class JPARepliedMessage  implements java.io.Serializable {


     private Integer id;
     private JPAMessage JPAMessage;
     private String fromAdr;
     private String body;

    public JPARepliedMessage() {
    }

	
    public JPARepliedMessage(JPAMessage JPAMessage, String fromAdr) {
        this.JPAMessage = JPAMessage;
        this.fromAdr = fromAdr;
    }
    public JPARepliedMessage(JPAMessage JPAMessage, String fromAdr, String body) {
       this.JPAMessage = JPAMessage;
       this.fromAdr = fromAdr;
       this.body = body;
    }
   
     @GenericGenerator(name="generator", strategy="increment")@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MESSAGE_ID", nullable=false)
    public JPAMessage getJPAMessage() {
        return this.JPAMessage;
    }
    
    public void setJPAMessage(JPAMessage JPAMessage) {
        this.JPAMessage = JPAMessage;
    }

    
    @Column(name="FROM_ADR", nullable=false)
    public String getFromAdr() {
        return this.fromAdr;
    }
    
    public void setFromAdr(String fromAdr) {
        this.fromAdr = fromAdr;
    }

    
    @Column(name="BODY", length=30000)
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }




}


