package at.fhv.xmltool.addressbook.jpa;
// Generated 15.01.2018 20:24:17 by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * JPAAddress generated by hbm2java
 */
@Entity
@Table(name="ADDRESSES"
    ,schema="APP"
)
public class JPAAddress  implements java.io.Serializable {


     private Integer id;
     private JPAPerson JPAPerson;
     private String street;
     private String zip;
     private String city;
     private String country;

    public JPAAddress() {
    }

	
    public JPAAddress(JPAPerson JPAPerson, String street, String zip, String city) {
        this.JPAPerson = JPAPerson;
        this.street = street;
        this.zip = zip;
        this.city = city;
    }
    public JPAAddress(JPAPerson JPAPerson, String street, String zip, String city, String country) {
       this.JPAPerson = JPAPerson;
       this.street = street;
       this.zip = zip;
       this.city = city;
       this.country = country;
    }
   
     @GenericGenerator(name="generator", strategy="increment")@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSON_ID", nullable=false)
    public JPAPerson getJPAPerson() {
        return this.JPAPerson;
    }
    
    public void setJPAPerson(JPAPerson JPAPerson) {
        this.JPAPerson = JPAPerson;
    }

    
    @Column(name="STREET", nullable=false)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="ZIP", nullable=false, length=16)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    
    @Column(name="CITY", nullable=false)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="COUNTRY")
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


