package at.fhv.xmltool.addressbook.jpa;
// Generated 15.01.2018 20:24:17 by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * JPAPerson generated by hbm2java
 */
@Entity
@Table(name="PERSONS"
    ,schema="APP"
)
public class JPAPerson  implements java.io.Serializable {


     private Integer id;
     private String firstname;
     private String lastname;
     private Set<JPAAddress> JPAAddresses = new HashSet<JPAAddress>(0);

    public JPAPerson() {
    }

	
    public JPAPerson(String firstname, String lastname) {
        this.firstname = firstname;
        this.lastname = lastname;
    }
    public JPAPerson(String firstname, String lastname, Set<JPAAddress> JPAAddresses) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.JPAAddresses = JPAAddresses;
    }
   
     @GenericGenerator(name="generator", strategy="increment")@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="FIRSTNAME", nullable=false)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="LASTNAME", nullable=false)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="JPAPerson")
    public Set<JPAAddress> getJPAAddresses() {
        return this.JPAAddresses;
    }
    
    public void setJPAAddresses(Set<JPAAddress> JPAAddresses) {
        this.JPAAddresses = JPAAddresses;
    }




}


